### ISSUE TITLE
FUNDNA EXE Generation Error

### ISSUE THREAD

**Issue by jphuse** [CUT-Labs/FUNDNA#2]
- When using the FUNDNA bash script to generate an exe version of the software, it is unable to with the following error and trace:

**Failed to execute script 'gui' due to unhandled exception: No module named 'schemdraw'**
```
Traceback (most recent call last):
  File "gui.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Util.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'schemdraw'
```

**Comment by jphuse** [comment]
This issue has been fixed in the release 1.5 -- nuskell integration
